### PR TITLE
Remove hardcoded Courier font family.

### PR DESCRIPTION
**Pull request by HBBrennan**
On Firefox, setting the Courier font family results in a 1.2 line spacing. This
does not look good.

### CODE REVIEW

**Comment by HBBrennan** [comment]
Firefox Nightly: Mozilla Firefox 106.0a1

### After
Artem_After

**Comment by FineFindus** [comment]
Thank you, it definitely looks better. Please make sure all tests pass.

**Comment by HBBrennan** [comment]
> Thank you, it definitely looks better. Please make sure all tests pass.

test result: ok. 41 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.35s

Added pretty_assertions so I could figure out what was wrong with the tests.

**Comment by FineFindus** [comment]
Thanks again. And nice cat.

**Pull request merged**
